server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
        #  uri: https://github.com/Djunnni/Practice_spring-cloud-config
        # uri: file:///Users/dongjoonlee/Desktop/git-local-repo #master????? cloud-config?? main? ?? ??? ??? ? ??.
        native:
          search-locations: file:///Users/dongjoonlee/Desktop/git-local-repo
  profiles:
    active: native
