server:
  port: 0

spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.orderservice: debug